export const simulatedParams = {
    rooms: [
        {
            id: 7,
            name: "Test room 1",
            camera: {
                position: {
                    x: 0,
                    y: 0,
                    z: 0,
                },
                rotation: {
                    x: 0,
                    y: 15,
                    z: 0,
                },
            },
            panels: [
                {
                    color: "#0000ff",
                    content: "",
                    depth: 0.1,
                    height: 5,
                    id: 27,
                    image: {
                        assetId: "url",
                        url: "test1.jpg",
                    },
                    isTransitionEnabled: false,
                    label: {
                        color: "#00f622f",
                        disable: false,
                        position: null,
                        rotation: { x: 0, y: 0, z: 0 },
                        scale: { x: 1, y: 3, z: 1 },
                        value: "Projector",
                        width: 12,
                    },
                    opacity: 0.75,
                    padding: 1,
                    panelName: "Projector",
                    position: {
                        x: -15,
                        y: 7.9,
                        z: 0,
                    },
                    remote: {
                        animationDisable: false,
                        animationImageId: "#glow",
                        animationSpeed: 1000,
                        animationType: "glowing",
                        assetId: "url",
                        disable: false,
                        position: {
                            x: -4.43,
                            y: 2.1,
                            z: 3,
                        },
                        remoteModelId: "#ring",
                        rotation: {
                            x: -90,
                            y: -90,
                            z: 0,
                        },
                        scale: {
                            x: 4,
                            y: 4,
                            z: 4,
                        },
                    },
                    rotation: {
                        x: 0,
                        y: 90,
                        z: 0,
                    },
                    scale: {
                        x: 1,
                        y: 1.1,
                        z: 1,
                    },
                    source: {
                        assetId: "#source27",
                    },
                    target: {
                        action: "start",
                        id: 27,
                        panelName: "Projector",
                        type: "projector",
                        url: null,
                    },
                    type: "projector",
                    video: {
                        assetId: "#",
                    },
                    width: 7,
                },
                {
                    color: "#808080",
                    content: "",
                    depth: 0.1,
                    height: 5,
                    id: 25,
                    image: {
                        assetId: "#door25",
                        url: "door25.jpg",
                    },
                    isTransitionEnabled: true,
                    label: {
                        color: "#0000000",
                        disable: false,
                        position: null,
                        rotation: { x: 0, y: 0, z: 0 },
                        scale: { x: 1, y: 1, z: 1 },
                        value: "Door 2 1",
                        width: 12,
                    },
                    opacity: 1,
                    padding: 0,
                    panelName: "Door 2 1",
                    position: {
                        x: -3,
                        y: 1.6,
                        z: -1.44,
                    },
                    remote: {
                        animationDisable: false,
                        animationImageId: "#glow",
                        animationSpeed: 100,
                        animationType: "glowing",
                        assetId: "url",
                        disable: false,
                        position: {
                            x: -0.7,
                            y: 4,
                            z: -8.9,
                        },
                        remoteModelId: "#ring",
                        rotation: {
                            x: -90,
                            y: 0,
                            z: 180,
                        },
                        scale: {
                            x: 10,
                            y: 10,
                            z: 10,
                        },
                    },
                    rotation: {
                        x: 0,
                        y: 90,
                        z: 0,
                    },
                    scale: {
                        x: 0.2,
                        y: 0.2,
                        z: 0.2,
                    },
                    source: {
                        assetId: "#source25",
                    },
                    target: {
                        action: "enter",
                        id: 8,
                        panelName: "Door 2 1",
                        type: "room",
                        url: null,
                    },
                    type: "door",
                    video: {
                        assetId: "#video25",
                        // assetUrl: "url25",
                    },
                    width: 3,
                },
                {
                    color: "#808080",
                    content: "",
                    depth: 0.1,
                    height: 5,
                    id: 31,
                    image: {
                        assetId: "#projector31",
                        url: "projector31.jpg",
                    },
                    isTransitionEnabled: false,
                    label: {
                        color: "#0000000",
                        disable: false,
                        position: null,
                        rotation: { x: 0, y: 0, z: 0 },
                        scale: { x: 1, y: 1, z: 1 },
                        value: "Projector",
                        width: 12,
                    },
                    opacity: 0.75,
                    padding: 0.2,
                    panelName: "Projector",
                    position: {
                        x: -15,
                        y: 3.1,
                        z: 7.2,
                    },
                    remote: {
                        animationDisable: true,
                        animationImageId: "#glow",
                        animationSpeed: 1000,
                        animationType: "glowing",
                        assetId: "url",
                        disable: false,
                        position: {
                            x: -0.68,
                            y: 0,
                            z: 0.65,
                        },
                        remoteModelId: "#ring",
                        rotation: {
                            x: 0,
                            y: 0,
                            z: 0,
                        },
                        scale: {
                            x: 4,
                            y: 4,
                            z: 4,
                        },
                    },
                    rotation: {
                        x: 0,
                        y: 90,
                        z: 0,
                    },
                    scale: {
                        x: 1,
                        y: 1,
                        z: 1,
                    },
                    source: {
                        assetId: "#source31",
                    },
                    target: {
                        action: "start",
                        id: 31,
                        panelName: "Projector",
                        type: "projector",
                        url: null,
                    },
                    type: "projector",
                    video: {
                        assetId: "#",
                    },
                    width: 7,
                },
                {
                    color: "#808080",
                    content: "",
                    depth: 0.1,
                    height: 5,
                    id: 33,
                    image: {
                        assetId: "#door33",
                        url: "door33.jpg",
                    },
                    isTransitionEnabled: true,
                    label: {
                        color: "#0000000",
                        disable: true,
                        position: null,
                        rotation: { x: 0, y: 0, z: 0 },
                        scale: { x: 1, y: 1, z: 1 },
                        value: "to Second",
                        width: 12,
                    },
                    opacity: 1,
                    padding: 0,
                    panelName: "to Second",
                    position: {
                        x: -11.5,
                        y: 0,
                        z: -10,
                    },
                    remote: {
                        animationDisable: false,
                        animationImageId: "#glow",
                        animationSpeed: 1000,
                        animationType: "glowing",
                        assetId: "url",
                        disable: true,
                        position: {
                            x: -5,
                            y: 0,
                            z: -4,
                        },
                        remoteModelId: "#ring",
                        rotation: {
                            x: 0,
                            y: 0,
                            z: 0,
                        },
                        scale: {
                            x: 4,
                            y: 4,
                            z: 4,
                        },
                    },
                    rotation: {
                        x: 0,
                        y: 50,
                        z: 0,
                    },
                    scale: {
                        x: 1,
                        y: 1,
                        z: 1,
                    },
                    source: {
                        assetId: "#source33",
                    },
                    target: {
                        action: "enter",
                        id: 9,
                        panelName: "to Second",
                        type: "room",
                        url: null,
                    },
                    type: "door",
                    video: {
                        assetId: "#video33",
                        // assetUrl: "url33",
                    },
                    width: 3,
                },
            ],
            sky: {
                assetId: "#room7",
                assetUrl: "room7.jpg",
            },
        },
        {
            id: 8,
            name: "Test room 2",
            camera: {
                position: {
                    x: 0,
                    y: 0,
                    z: 0,
                },
                rotation: {
                    x: 0,
                    y: 90,
                    z: 0,
                },
            },
            panels: [
                {
                    color: "#808080",
                    content: "",
                    depth: 0.1,
                    height: 5,
                    id: 26,
                    image: {
                        assetId: "#test26",
                        url: "test26.jpg",
                    },
                    isTransitionEnabled: false,
                    label: {
                        color: "#0000000",
                        disable: true,
                        position: null,
                        rotation: { x: 0, y: 0, z: 0 },
                        scale: { x: 1, y: 1, z: 1 },
                        value: "Door 1 2",
                        width: 12,
                    },
                    opacity: 1,
                    padding: 0,
                    panelName: "Door 1 2",
                    position: {
                        x: -15,
                        y: 0,
                        z: -10,
                    },
                    remote: {
                        animationDisable: true,
                        animationImageId: "#glow",
                        animationSpeed: 1000,
                        animationType: "shaking",
                        assetId: "#remote26",
                        disable: true,
                        position: {
                            x: -5,
                            y: 0,
                            z: -4,
                        },
                        remoteModelId: "#ring",
                        rotation: {
                            x: 0,
                            y: 0,
                            z: 0,
                        },
                        scale: {
                            x: 4,
                            y: 4,
                            z: 4,
                        },
                    },
                    rotation: {
                        x: 0,
                        y: 90,
                        z: 0,
                    },
                    scale: {
                        x: 1,
                        y: 1,
                        z: 1,
                    },
                    source: {
                        assetId: "#source26",
                    },
                    target: {
                        action: "enter",
                        id: 7,
                        panelName: "Door 1 2",
                        type: "room",
                        url: null,
                    },
                    type: "door",
                    video: {
                        assetId: "#video26",
                        // assetUrl: "",
                    },
                    width: 3,
                },
                {
                    color: "#808080",
                    content:
                        "PHA+c2ZoIDxzdHJvbmc+c2ZzamhmJm5ic3A7PC9zdHJvbmc+a3NqaCA8dT5ma3MmbmJzcDs8L3U+amtmIDxlbT5ocyZuYnNwOzwvZW0+aGZrIDxzdHJvbmc+aHNmaCZuYnNwOzwvc3Ryb25nPmtzIDxzdHJvbmc+aGZraCZuYnNwOzwvc3Ryb25nPnNrIDxzdHJvbmc+aGZrcyZuYnNwOzwvc3Ryb25nPmhmIDxzdHJvbmc+aHMmbmJzcDs8L3N0cm9uZz5oZmprIDxzdHJvbmc+c2hmJm5ic3A7PC9zdHJvbmc+aHNraiBmIDxzdHJvbmc+c2hmaCZuYnNwOzwvc3Ryb25nPnNqayBoZmtqIDxzdHJvbmc+aHNramYmbmJzcDs8L3N0cm9uZz5oYXNramhma2FzamggPHN0cm9uZz5ma2FzaCZuYnNwOzwvc3Ryb25nPmtmaCA8c3Ryb25nPmFza2poJm5ic3A7PC9zdHJvbmc+Zmtqc2EgZmsgPHN0cm9uZz5oc2FramgmbmJzcDs8L3N0cm9uZz5ma2ogc2ZraiA8c3Ryb25nPmhza2phJm5ic3A7PC9zdHJvbmc+aGZrYWpzIGZraiA8c3Ryb25nPmhhc2tqPC9zdHJvbmc+IDxzdHJvbmc+ZmhranNhaCZuYnNwOzwvc3Ryb25nPmZranNhIDxzdHJvbmc+a2ZqaCZuYnNwOzwvc3Ryb25nPnNha2pmaCA8c3Ryb25nPmtqc2EmbmJzcDs8L3N0cm9uZz5ma2pzaCA8c3Ryb25nPmZramhzJm5ic3A7PC9zdHJvbmc+YWtmamggPHN0cm9uZz5zYWtqZmgmbmJzcDs8L3N0cm9uZz5qc2thaGYgPHN0cm9uZz5sa2phc2gmbmJzcDs8L3N0cm9uZz5ma2pzaCA8c3Ryb25nPmZramhhcyZuYnNwOzwvc3Ryb25nPmtmamggPHN0cm9uZz5hc2tqZmgmbmJzcDs8L3N0cm9uZz5ranNhaCA8c3Ryb25nPmZqJm5ic3A7PC9zdHJvbmc+aHNhZmxoc2prYSA8c3Ryb25nPmZoamtoZmsmbmJzcDs8L3N0cm9uZz5zaGdrbGpkc2ggPHN0cm9uZz5na2pkZmgmbmJzcDs8L3N0cm9uZz5na2pkaGZnIDxzdHJvbmc+a2pkcyZuYnNwOzwvc3Ryb25nPmZna2poIDxzdHJvbmc+ZGZqa2c8L3N0cm9uZz4gaGRza2ZqaCA8c3Ryb25nPmdramQmbmJzcDs8L3N0cm9uZz5na2pkaCA8c3Ryb25nPmdraCZuYnNwOzwvc3Ryb25nPmRma2doIDxzdHJvbmc+ZHNrbGxna2RnamsmbmJzcDs8L3N0cm9uZz5kZ2prZGprIDxzdHJvbmc+Z2prZGgmbmJzcDs8L3N0cm9uZz5na2poZ2w7PHN0cm9uZz5rc2ombmJzcDs8L3N0cm9uZz5sO2tqIDxzdHJvbmc+Z2tqJm5ic3A7PC9zdHJvbmc+O2xnamx4a2dqIDxzdHJvbmc+bHNhazwvc3Ryb25nPjtnaiBsaWp0dSA8c3Ryb25nPml1dCZuYnNwOzwvc3Ryb25nPm9panQgbGtzO2FqZmc7bGtzYSBqZ2w7a2FzaiBnbDtzYSB1amdsa2ZhamcgbGs7YWZqZyBrbDtmamcgbGtmamcgbDtrZWpyIGdscDtraSBldXJ0bDtpIGFzamdsazwvcD48cD48YnI+PC9wPjxwPjxpbWcgc3JjPSIvdXBsb2Fkcy8xL2Zyb2FsYV9pbWFnZXMvMTExNjBlMDJmNmFmMzQ2YTMwZmVkZGNkN2VhNjg5ZjAtMjAyMTAzMjMxOTEyLmpwZWc/djEiIHN0eWxlPSJ3aWR0aDogMTA1M3B4OyIgY2xhc3M9ImZyLWZpYyBmci1kaWIiPjwvcD4=",
                    depth: 0.1,
                    height: 5,
                    id: 28,
                    image: {
                        assetId: "#screen28",
                        url: "screen28.jpg",
                    },
                    isTransitionEnabled: false,
                    label: {
                        color: "#0000000",
                        disable: true,
                        position: null,
                        rotation: { x: 0, y: 0, z: 0 },
                        scale: { x: 1, y: 1, z: 1 },
                        value: "Html",
                        width: 12,
                    },
                    opacity: 0.75,
                    padding: 0.2,
                    panelName: "Html",
                    position: {
                        x: -15,
                        y: 6,
                        z: -7.5,
                    },
                    remote: {
                        animationDisable: false,
                        animationImageId: "#glow",
                        animationSpeed: 1000,
                        animationType: "glowing",
                        assetId: "#remote28",
                        disable: false,
                        position: {
                            x: -8.1,
                            y: 0,
                            z: 1.4,
                        },
                        remoteModelId: "#ring",
                        rotation: {
                            x: 0,
                            y: 0,
                            z: 0,
                        },
                        scale: {
                            x: 8,
                            y: 8,
                            z: 8,
                        },
                    },
                    rotation: {
                        x: 0,
                        y: 90,
                        z: 0,
                    },
                    scale: {
                        x: 1,
                        y: 1,
                        z: 1,
                    },
                    source: {
                        assetId: "#source28",
                    },
                    target: {
                        action: "zoom_in",
                        id: 28,
                        panelName: "Html",
                        type: "billboard",
                        url: null,
                    },
                    type: "billboard",
                    video: {
                        assetId: "#",
                    },
                    width: 7,
                },
                {
                    color: "#808080",
                    content: "",
                    depth: 0.1,
                    height: 5,
                    id: 30,
                    image: {
                        assetId: "#screen30",
                        url: "screen30.jpg",
                    },
                    isTransitionEnabled: false,
                    label: {
                        color: "#0000000",
                        disable: false,
                        position: null,
                        rotation: { x: 0, y: 0, z: 0 },
                        scale: { x: 1, y: 1, z: 1 },
                        value: "Screen 1",
                        width: 12,
                    },
                    opacity: 0.75,
                    padding: 0.2,
                    panelName: "Screen 1",
                    position: {
                        x: -15,
                        y: 3,
                        z: 1,
                    },
                    remote: {
                        animationDisable: false,
                        animationImageId: "#glow",
                        animationSpeed: 1000,
                        animationType: "glowing",
                        assetId: "#remote30",
                        disable: false,
                        position: {
                            x: -5,
                            y: 0,
                            z: 2.1,
                        },
                        remoteModelId: "#ring",
                        rotation: {
                            x: 0,
                            y: 0,
                            z: 0,
                        },
                        scale: {
                            x: 20,
                            y: 4,
                            z: 10,
                        },
                    },
                    rotation: {
                        x: 0,
                        y: 90,
                        z: 0,
                    },
                    scale: {
                        x: 1,
                        y: 1,
                        z: 1,
                    },
                    source: {
                        assetId: "#source30",
                    },
                    target: {
                        action: "open",
                        id: 30,
                        panelName: "Screen 1",
                        type: "iframe",
                        url: "/a3d",
                    },
                    type: "screen",
                    video: {
                        assetId: "#",
                    },
                    width: 7,
                },
                {
                    color: "#808080",
                    content:
                        "PHA+Jmx0O3Agc3R5bGU9JnF1b3Q7TWFyZ2luOjA7LXdlYmtpdC10ZXh0LXNpemUtYWRqdXN0Om5vbmU7LW1zLXRleHQtc2l6ZS1hZGp1c3Q6bm9uZTttc28tbGluZS1oZWlnaHQtcnVsZTpleGFjdGx5O2ZvbnQtZmFtaWx5OnZlcmRhbmEsIGdlbmV2YSwgc2Fucy1zZXJpZjtsaW5lLWhlaWdodDozNnB4O2NvbG9yOiMzMzMzMzM7Zm9udC1zaXplOjI0cHg7JnF1b3Q7Jmd0OyZsdDtzdHJvbmcmZ3Q7JmFtcDtuYnNwOyAmYW1wO25ic3A7ICZhbXA7bmJzcDsgJmFtcDtuYnNwOyZsdDsvc3Ryb25nJmd0Ozxicj4mbmJzcDsgJm5ic3A7ICZsdDtpZnJhbWUgc3JjPSZxdW90O2h0dHBzOi8vcGxheWVyLnZpbWVvLmNvbS92aWRlby81NDIwMTU5MzUmcXVvdDsgZnJhbWVib3JkZXI9JnF1b3Q7MCZxdW90OyBhbGxvd2Z1bGxzY3JlZW49JnF1b3Q7JnF1b3Q7IGNsYXNzPSZxdW90O2ZyLWRyYWdnYWJsZSZxdW90OyBzdHlsZT0mcXVvdDt3aWR0aDogMTAwdnc7IGhlaWdodDogMTAwdmg7JnF1b3Q7Jmd0OyZsdDsvaWZyYW1lJmd0OyZsdDsvcCZndDs8YnI+PGJyPiZsdDtwIHN0eWxlPSZxdW90O01hcmdpbjowOy13ZWJraXQtdGV4dC1zaXplLWFkanVzdDpub25lOy1tcy10ZXh0LXNpemUtYWRqdXN0Om5vbmU7bXNvLWxpbmUtaGVpZ2h0LXJ1bGU6ZXhhY3RseTtmb250LWZhbWlseTp2ZXJkYW5hLCBnZW5ldmEsIHNhbnMtc2VyaWY7bGluZS1oZWlnaHQ6MzZweDtjb2xvcjojMzMzMzMzO2ZvbnQtc2l6ZToyNHB4OyZxdW90OyZndDsmbHQ7c3Ryb25nJmd0OyZhbXA7bmJzcDsgJmFtcDtuYnNwOyAmYW1wO25ic3A7ICZhbXA7bmJzcDsmbHQ7L3N0cm9uZyZndDs8YnI+Jm5ic3A7ICZuYnNwOyAmbHQ7aWZyYW1lIHNyYz0mcXVvdDtodHRwczovL3BsYXllci52aW1lby5jb20vdmlkZW8vNTQyMTE2Mjk2JnF1b3Q7IGZyYW1lYm9yZGVyPSZxdW90OzAmcXVvdDsgYWxsb3dmdWxsc2NyZWVuPSZxdW90OyZxdW90OyBjbGFzcz0mcXVvdDtmci1kcmFnZ2FibGUmcXVvdDsgc3R5bGU9JnF1b3Q7d2lkdGg6IDEwMHZ3OyBoZWlnaHQ6IDEwMHZoOyZxdW90OyZndDsmbHQ7L2lmcmFtZSZndDs8YnI+Jmx0Oy9wJmd0OzwvcD4=",
                    depth: 0.1,
                    height: 5,
                    id: 32,
                    image: {
                        assetId: "#screen32",
                        url: "screen32.jpg",
                    },
                    isTransitionEnabled: false,
                    label: {
                        color: "#0000000",
                        disable: false,
                        position: null,
                        rotation: { x: 0, y: 0, z: 0 },
                        scale: { x: 1, y: 1, z: 1 },
                        value: "test VIDEMO",
                        width: 12,
                    },
                    opacity: 0.75,
                    padding: 0.2,
                    panelName: "Test VIDEMO",
                    position: {
                        x: -15,
                        y: 11.75,
                        z: -0.5,
                    },
                    remote: {
                        animationDisable: false,
                        animationImageId: "#glow",
                        animationSpeed: 1000,
                        animationType: "glowing",
                        assetId: "#remote32",
                        disable: false,
                        position: {
                            x: -5,
                            y: 0,
                            z: 0,
                        },
                        remoteModelId: "#ring",
                        rotation: {
                            x: 0,
                            y: 0,
                            z: 0,
                        },
                        scale: {
                            x: 4,
                            y: 4,
                            z: 4,
                        },
                    },
                    rotation: {
                        x: 0,
                        y: 90,
                        z: 0,
                    },
                    scale: {
                        x: 1,
                        y: 1,
                        z: 1,
                    },
                    source: {
                        assetId: "#source32",
                    },
                    target: {
                        action: "zoom_in",
                        id: 32,
                        panelName: "Test VIDEMO",
                        type: "billboard",
                        url: null,
                    },
                    type: "billboard",
                    video: {
                        assetId: "#",
                    },
                    width: 3,
                },
                {
                    color: "#808080",
                    content: "",
                    depth: 0.1,
                    height: 5,
                    id: 29,
                    image: {
                        assetId: "#screen29",
                        url: "screen29.jpg",
                    },
                    isTransitionEnabled: false,
                    label: {
                        color: "#0000000",
                        disable: false,
                        position: null,
                        rotation: { x: 0, y: 0, z: 0 },
                        scale: { x: 1, y: 1, z: 1 },
                        value: "Screen",
                        width: 12,
                    },
                    opacity: 0.75,
                    padding: 0.2,
                    panelName: "Screen",
                    position: {
                        x: -15,
                        y: 0,
                        z: 7.1,
                    },
                    remote: {
                        animationDisable: false,
                        animationImageId: "#glow",
                        animationSpeed: 1000,
                        animationType: "glowing",
                        assetId: "#remote29",
                        disable: false,
                        position: {
                            x: -5,
                            y: 0,
                            z: -1.8,
                        },
                        remoteModelId: "#ring",
                        rotation: {
                            x: 0,
                            y: 0,
                            z: 0,
                        },
                        scale: {
                            x: 4,
                            y: 4,
                            z: 4,
                        },
                    },
                    rotation: {
                        x: 0,
                        y: 90,
                        z: 0,
                    },
                    scale: {
                        x: 1,
                        y: 1,
                        z: 1,
                    },
                    source: {
                        assetId: "#source29",
                    },
                    target: {
                        action: "open",
                        id: 29,
                        panelName: "Screen",
                        type: "iframe",
                        url: "/",
                    },
                    type: "screen",
                    video: {
                        assetId: "#",
                    },
                    width: 7,
                },
            ],
            sky: {
                assetId: "#room8",
                assetUrl: "room8.jpg",
            },
        },
        {
            id: 9,
            name: "Second",
            camera: {
                position: {
                    x: 0,
                    y: 0,
                    z: 0,
                },
                rotation: {
                    x: 0,
                    y: -175,
                    z: 0,
                },
            },
            panels: [
                {
                    color: "#808080",
                    content: "",
                    depth: 0.1,
                    height: 5,
                    id: 36,
                    image: {
                        assetId: "#door36",
                        url: "door36.jpg",
                    },
                    isTransitionEnabled: false,
                    label: {
                        color: "#0000000",
                        disable: true,
                        position: null,
                        rotation: { x: 0, y: 0, z: 0 },
                        scale: { x: 1, y: 1, z: 1 },
                        value: null,
                        width: 12,
                    },
                    opacity: 1,
                    padding: 0,
                    panelName: "Door",
                    position: {
                        x: -15,
                        y: 0,
                        z: -10,
                    },
                    remote: {
                        animationDisable: false,
                        animationImageId: "#glow",
                        animationSpeed: 1000,
                        animationType: "glowing",
                        assetId: "#remote36",
                        disable: false,
                        position: {
                            x: -4,
                            y: 0,
                            z: 1,
                        },
                        remoteModelId: "#ring",
                        rotation: {
                            x: 0,
                            y: 0,
                            z: 0,
                        },
                        scale: {
                            x: 4,
                            y: 4,
                            z: 4,
                        },
                    },
                    rotation: {
                        x: 0,
                        y: 90,
                        z: 0,
                    },
                    scale: {
                        x: 1,
                        y: 1,
                        z: 1,
                    },
                    source: {
                        assetId: "#source36",
                    },
                    target: {
                        action: "enter",
                        id: 7,
                        panelName: "Door",
                        type: "room",
                        url: null,
                    },
                    type: "door",
                    video: {
                        assetId: "#video36",
                        // assetUrl: "",
                    },
                    width: 3,
                },
                {
                    color: "#808080",
                    content: "",
                    depth: 0.1,
                    height: 5,
                    id: 35,
                    image: {
                        assetId: "#door35",
                        url: "door35.jpg",
                    },
                    isTransitionEnabled: false,
                    label: {
                        color: "#0000000",
                        disable: true,
                        position: null,
                        rotation: { x: 0, y: 0, z: 0 },
                        scale: { x: 1, y: 1, z: 1 },
                        value: "TEST",
                        width: 12,
                    },
                    opacity: 0.75,
                    padding: 0.2,
                    panelName: "TEST",
                    position: {
                        x: -15,
                        y: 0,
                        z: 0,
                    },
                    remote: {
                        animationDisable: true,
                        animationImageId: "#glow",
                        animationSpeed: 100,
                        animationType: "blinking",
                        assetId: "#remote35",
                        disable: false,
                        position: {
                            x: -5,
                            y: 0,
                            z: 0,
                        },
                        remoteModelId: "#ring",
                        rotation: {
                            x: 0,
                            y: 0,
                            z: 0,
                        },
                        scale: {
                            x: 4,
                            y: 4,
                            z: 4,
                        },
                    },
                    rotation: {
                        x: 0,
                        y: 90,
                        z: 0,
                    },
                    scale: {
                        x: 1,
                        y: 1,
                        z: 1,
                    },
                    source: {
                        assetId: "#source35",
                    },
                    target: {
                        action: "start",
                        id: 35,
                        panelName: "TEST",
                        type: "projector",
                        url: null,
                    },
                    type: "projector",
                    video: {
                        assetId: "#",
                    },
                    width: 7,
                },
                {
                    color: "#808080",
                    content: "",
                    depth: 0.1,
                    height: 6,
                    id: 34,
                    image: {
                        assetId: "#door34",
                        url: "door34.jpg",
                    },
                    isTransitionEnabled: true,
                    label: {
                        color: "#0000000",
                        disable: true,
                        position: null,
                        rotation: { x: 0, y: 0, z: 0 },
                        scale: { x: 1, y: 1, z: 1 },
                        value: null,
                        width: 12,
                    },
                    opacity: 1,
                    padding: 0,
                    panelName: "to main",
                    position: {
                        x: 7.9,
                        y: 0.8,
                        z: 8.05,
                    },
                    remote: {
                        animationDisable: true,
                        animationImageId: "#glow",
                        animationSpeed: 1000,
                        animationType: "glowing",
                        assetId: "#remote34",
                        disable: false,
                        position: {
                            x: -5,
                            y: 0,
                            z: -6,
                        },
                        remoteModelId: "#ring",
                        rotation: {
                            x: 0,
                            y: 90,
                            z: 0,
                        },
                        scale: {
                            x: 4,
                            y: 4,
                            z: 4,
                        },
                    },
                    rotation: {
                        x: 0,
                        y: 90,
                        z: 0,
                    },
                    scale: {
                        x: 0.9,
                        y: 0.9,
                        z: 1,
                    },
                    source: {
                        assetId: "#source34",
                    },
                    target: {
                        action: "enter",
                        id: 7,
                        panelName: "to main",
                        type: "room",
                        url: null,
                    },
                    type: "door",
                    video: {
                        assetId: "#video34",
                        // assetUrl: "",
                    },
                    width: 7,
                },
            ],
            sky: {
                assetId: "#room9",
                assetUrl: "room9.jpg",
            },
        },
    ],
};
