import {
    Grid,
    Briefcase,
    Users,
    Calendar,
    Settings,
    ChevronLeft,
    ChevronDown,
    ChevronRight,
    Edit3,
    Trash2,
    Plus,
    Search,
    X,
    Menu,
    ArrowLeft,
    Eye,
    EyeOff,
} from "react-feather";

import { ListTree } from "./app-custom-icons";
import { AppIconMap } from "../../models";

export const appIconMap: AppIconMap = {
    dashboard: Grid,
    Grid,
    X,
    Eye,
    EyeOff,
    ArrowLeft,
    Menu,
    Search,
    sponsors: Briefcase,
    Briefcase,
    attendees: Users,
    Users,
    myAgenda: Calendar,
    Calendar,
    administrator: Settings,
    Settings,
    back: ChevronLeft,
    ChevronLeft,
    next: ChevronRight,
    ChevronRight,
    ChevronDown,
    edit: Edit3,
    Edit3,
    delete: Trash2,
    Trash2,
    add: Plus,
    Plus,
    ListTree,
};
